development:
  sessions:
    default:
      database: tracco_dev
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: tracco_test
      hosts:
        - localhost:27017


production:
  autocreate_indexes: true
  persist_in_safe_mode: true

  sessions:
    default:
      database: tracco_production
      hosts:
        - localhost:27017
