development:
  sessions:
    default:
      database: trello_effort_tracker_dev
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: trello_effort_tracker_test
      hosts:
        - localhost:27017


production:
  sessions:
    default:
      database: trello_effort_tracker_production
      hosts:
        - localhost:27017
