development:
  sessions:
     default:
       database: trello_dev
       hosts:
         - localhost:27017

test:
  sessions:
     default:
       database: trello_test
       hosts:
         - localhost:27017
